[versions]
minecraft = "26.1-pre-2"

# Xplat
neoform = "26.1-pre-2-1"
mixin = "0.16.5+mixin.0.8.7"
mixin-extras = "0.5.0"

# Fabric
fabric-loader = "0.18.4"
fabric-api = "0.143.14+26.1"
mod-menu = "18.0.0-alpha.6"

# NeoForge
neoforge = "26.1.0.0-alpha.14+snapshot-11"

# Gradle
loom = "1.15.+"
moddev = "2.0.140"
mod-publish = "1.1.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "mixin" }
mixin-extras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixin-extras" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
mod-menu = { module = "com.terraformersmc:modmenu", version.ref = "mod-menu" }

[plugins]
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
mod-publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
