modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
issueTrackerURL="https://github.com/GreenhouseTeam/enchantment-disable-tag/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://modrinth.com/project/enchantment-disable-tag/"
logoFile="${mod_id}.png"
logoBlur=false
credits="MerchantPug"
authors="Greenhouse Team"
description='''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[accessTransformers]]
file="${mod_id}.cfg"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_loader_version_range}"
ordering="NONE"
side="SERVER"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="SERVER"